### ISSUE TITLE
Disable/enable foreign key checks before/after migrations

### ISSUE THREAD

**Issue by hemorej** [phalcon/phalcon-devtools#635] opened 2016-03-22 17:06 UTC
I just wasted a few hours trying to figure out why my migrations kept generating 

`Error: SQLSTATE[HY000]: General error: 1215 Cannot add foreign key constraint` 

even when the DDL was correct and the database fresh. I had to manually run

`mysql> SET GLOBAL FOREIGN_KEY_CHECKS=0 ;`

before then enable it after the migration for them to run.

Why isn't this done automatically by Phalcon ?

**Comment by rianorie** [comment] 2016-03-22 17:10
Because it can harm the integrity of your database?

**Comment by hemorej** [comment] 2016-03-22 17:14
So then why are the tables created in a seemingly random order ? Not a single foreign key constraint could be added, on empty tables in a new database, until I did this

**Comment by rianorie** [comment] 2016-03-22 17:15
Share your file tree and if possible migration files as well for insights.

**Comment by hemorej** [comment] 2016-03-22 17:20
File tree ? Do you mean the structure in the migrations directory ?

**Comment by rianorie** [comment] 2016-03-22 18:46
Yes, so we can see the filenames and directories

**Comment by rianorie** [comment] 2016-03-29 08:10
Closing this for the time being, given the private nature of the info in the project @hemorej and I discussed it over mail and came up with a solution.

In the long run the migrations will need to figure out dependencies if we can make that work.

**Closed by rianorie** 2016-03-29 08:10 UTC

**Comment by jorwan** [comment] 2018-05-09 13:53
hi, same problem here. whoe did you fix it ?
Thanks

**Comment by ZPaskov-GEA** [comment] 2021-03-17 14:00
Seems that the issue is dead.. but the problem persists. Even with latest version of DevTools, I'm not able to run the migrations without some hacks. Will this issue be fixed or not ?
