### ISSUE TITLE
Failed to create symbolic link .../phalcon-devtools/phalcon: File exists

### ISSUE THREAD

**Issue by Radio** [phalcon/phalcon-devtools#1318] opened 2019-09-26 13:27 UTC
### Expected and Actual Behavior

I am trying to install devtools following this instructions: https://docs.phalcon.io/3.4/en/devtools-installation#installation-macos

I'm getting error, below is my output:

```bash
$ . ./phalcon.sh

Phalcon Developer Tools Installer

Make sure phalcon.sh is in the same dir as phalcon file
and that you are running this with sudo or as root.

Installing Devtools...
Working dir is: <my_local_path>/phalcon-devtools
Failed to create symbolic link <my_local_path>/phalcon-devtools/phalcon: File exists
Exit.
```

`phalcon.sh` expects that `phalcon` file is not present in the repository root, while it is.

### Details

* Operating System: MacOS

**Comment by Jeckerson** [comment] 2019-09-26 14:46
What is phalcon-devtools version?

**Comment by Radio** [comment] 2019-09-26 14:47
I've tried on `master` and `v3.4.3`. Result is the same.

**Comment by Jeckerson** [comment] 2019-09-26 14:58
Current documentation is deprecated. Just write

```
rm -f /usr/bin/phalcon
ln -s phalcon-devtools-path/phalcon /usr/bin/phalcon
chmod ugo+x /usr/bin/phalcon
```

**Comment by Radio** [comment] 2019-09-26 15:02
Thanks for your response. After doing this and running `phalcon` I get:
```
$ phalcon
ERROR: Phalcon extension isn't installed, follow these instructions to install it: https://docs.phalconphp.com/en/latest/installation
```

**Comment by Jeckerson** [comment] 2019-09-26 15:05
Well, now you need to install the Phalcon. :nerd_face:

**Comment by Radio** [comment] 2019-09-26 15:51
Ah, you are right, sorry. I was thinking this was about the phalcon-devtools extension.

**Comment by sergeyklay** [comment] 2019-09-26 15:52
I'm closing since this is a not a bug report. Feel free to discuss on the [official forums](https://forum.phalconphp.com), and/or the internals repo.

**Closed by sergeyklay** 2019-09-26 15:52 UTC
Labels: Documentation, Question
