### ISSUE TITLE
JQuery version don't correspond to the static file.

### ISSUE THREAD

**Issue by yiivon** [phalcon/phalcon-devtools#752] opened 2016-08-12 09:13 UTC
**scripts\Phalcon\Web\JQuery.php on line 46 - 47** 
`
            copy($jqueryRoot . '/jquery-2.2.2.min.js', $jsJqueryDir . '/jquery-2.2.2.min.js');
            copy($jqueryRoot . '/jquery-2.2.2.min.map', $jsJqueryDir . '/jquery-2.2.2.min.map');
`
but files in directory **resources\jquery** are version **3.1.0**

**Comment by sergeyklay** [comment] 2016-08-12 09:19
@dschissler Could you please take a look?

**Comment by yiivon** [comment] 2016-08-12 09:31
![image](https://cloud.githubusercontent.com/assets/1287165/17618468/989dfede-60b2-11e6-996a-079cc25ea841.png)

**Comment by dschissler** [comment] 2016-08-12 11:36
This is a duplicate of #728 it is fixed in the 3.0.x branch.

**Comment by yiivon** [comment] 2016-08-12 11:46
GREAT!

**Closed** 2016-08-12 11:56 UTC
