### ISSUE TITLE
Model generation error in getter and setter name

### ISSUE THREAD

**Issue by nadorator** [phalcon/phalcon-devtools#1086] opened 2017-08-21 14:59 UTC
### Expected and Actual Behavior

> When using command line:

 phalcon model --name=robot --get-set 
I got caracter '-' in getter and setter function naming.

> ex: 
```php
/**
     * Method to set the value of field name
     *
     * @param string $name
     * @return $this
     */
    public function setName-($name)
    {
        $this->name = $name;

        return $this;
    }
```

### Details

The error is in Model.php source code where the delimiter for camelize function is 
```php
_-
```
 instead of 
```php
_
```
  It should be
```php
['_','-'] 
```
 
and Utils and Text class should be updated to use array delimiters instead of simple delimiter as those classes use explodes to identifies the delimiter passed through camelization. 

* System info and versions (if possible): (`phalcon info`)
* Phalcon Framework version: (`php --ri phalcon`)
* PHP Version: (`php -v`)
* Operating System:
* Server: Nginx | Apache | Other
* Other related info (Database, table schema):

**Comment by sergeysviridenko** [comment] 2017-08-23 15:46
I couldn't reproduce this issue. Could you provide more information for reproduce? Which version devtools do you use? Could you provide table from DB for reproducing?

**Comment by sergeysviridenko** [comment] 2017-09-13 13:16
I propose close this issue, because there is not any reaction. If issue appears again, we'll open new or reopen it.

**Closed** 2017-09-13 15:32 UTC
Labels: Models, Scaffold
