### ISSUE TITLE
Extends doesnt work for absolute namespace

### ISSUE THREAD

**Issue by cbichis** [phalcon/phalcon-devtools#833] opened 2016-09-17 13:42 UTC
Hi,

I am trying to generate some models which are extending one class from a completly different vendor:

```
phalcon model spec_color \
  --name=spec_color \
  --namespace=My\\Classified\\Models \
  --output=apps/classified/models \
  --get-set \
  --force \
  --camelize \
  --mapcolumn \
  --annotate \
  --extends=\\OtherVendor\\Model\\MultiLanguage \
  --doc
```

However, the class name is extending a wrong class:

``` php
namespace My\Classified\Models;

class SpecColor extends OtherVendor\Model\MultiLanguage
```

Instead of extending

``` php
class SpecColor extends \OtherVendor\Model\MultiLanguage
```

This is a bug maybe ?

**Comment by cbichis** [comment] 2016-09-17 15:23
Actually this seems to work if the model is not already defined.

**Comment by cbichis** [comment] 2016-09-17 15:23
Actually this works if the model is not already defined.

**Comment by sergeysviridenko** [comment] 2017-06-08 09:15
I couldn't reproduce it.

**Comment by sergeyklay** [comment] 2017-06-08 09:18
Can't reproduce. I want to close this issue because I don't want a bunch of these lying around.
I'm closing since this is a not a bug report. Feel free to discuss on the [official forums](https://forum.phalconphp.com), and/or the internals repo.

**Closed by sergeyklay** 2017-06-08 09:18 UTC
Labels: Bug - Medium, Models
