### ISSUE TITLE
Why we have to call the last morph function in the previous migration when rollback

### ISSUE THREAD

**Issue by zjcf** [phalcon/phalcon-devtools#1026] opened 2017-06-13 04:42 UTC
### Descripition

> When we run migration to rollback to a previous version, it will call the last morph function in the previous migration files after run the down method,  I got this by read the source code of Phalcon/Mvc/Model/Migration.php. I don't know why we have to do this, and I got problems in the following cases.

### Case
I have three migrations as follows:

> migration 1
```php
...
public function morph(){
    $this->morphTable('test', [
        'columns' => [
            new Column(
                'id',
                [   
                    'type' => Column::TYPE_INTEGER,
                    'notNull' => true,
                    'autoIncrement' => true,
                    'size' => 11, 
                    'first' => true
                ]   
            ),  
            new Column(
                'name',
                [   
                    'type' => Column::TYPE_VARCHAR,
                    'size' => 32, 
                    'after' => 'id'
                ]   
            )
        ],
        ...
    ]);
}
...
```
> migration 2
```php
public function up(){
    self::$_connect->execute("ALTER TABLE `test` ADD f1 VARCHAR(32) AFTER name");
}
public function down(){
    self::$_connect->execute("ALTER TABLE `test` DROP COLUMN f1");
}
```
> migration 3
```php
public function up(){
    self::$_connect->execute("ALTER TABLE `test` ADD f2 VARCHAR(32) AFTER f1");
}
public function down(){
    self::$_connect->execute("ALTER TABLE `test` DROP COLUMN f2");
}
```
In the above case, if I want to rollback migration to migration2 or migration1 version, it will get problems.  

If we only want to rollback to migration2, it will also drop column f1, because it called the morph method of migration1. 

If we want to rollback to migration1, it will get sql error when call the down method of migraiton2, because the field f1 was already droped after  migration3 rollback.

### Question
I can't understand why we need to call the morph function when rollback. This makes me feel confused whether I use the migrate tool correctly.

Sometimes, I have to keep the data of drop columns, so I can't only use the morph function to manage the table.

### Details
Phalcon DevTools Version: 3.1.2
Phalcon Version: 3.1.2

**Comment by sergeysviridenko** [comment] 2017-08-31 14:51
@zjcf could you provide please table SQL, SQL on every step for reproducing?

**Comment by sergeysviridenko** [comment] 2017-11-03 13:14
I propose close this issue. There isn't any reaction and question about product working is on the forum

**Comment by sergeyklay** [comment] 2017-11-04 20:54
I'm closing this issue due to the lack of any reaction. I'll open it again if the need arises

**Closed by sergeyklay** 2017-11-04 20:54 UTC
Labels: Migrations
