### ISSUE TITLE
404error: http://localhost/js/webtools.js?v=3.1.2  http://localhost/css/webtools.css?v=3.1.2 

### ISSUE THREAD

**Issue by lansn** [phalcon/phalcon-devtools#1007] opened 2017-04-11 02:12 UTC
### Expected and Actual Behavior

I use `phalcon.bat project learn --enable-webtools`, after the base url is `localhost/learn`, but url http://localhost/learn/webtools layout http://localhost/js/webtools.js?v=3.1.2 http://localhost/css/webtools.css?v=3.1.2  show 404 error, the css and js url wrong

### Details

* System info and versions (if possible): (`phalcon info`)
* Phalcon Framework version: (`php --ri phalcon`)
* PHP Version: (`php -v`)
* Operating System:
* Server: Nginx | Apache | Other
* Other related info (Database, table schema):

**Comment by sergeyklay** [comment] 2017-04-30 21:13
@lansn Actually we need more info to reproduce the issue. I don't have Windows, so I want to ask you to do this test:

1. Create a project
2. Then enable WebTools by using `phalcon.bat webtools enable`

Is this workaround works?

**Comment by sergeyklay** [comment] 2017-04-30 21:19
Also, as I remember @dschissler has changed the templates to use non-standard `baseUri`. In fact, since he did that I constantly hear about problems with this. Could you play just for test with `baseUri` (see application config).

**Comment by dschissler** [comment] 2017-04-30 23:48
@sergeyklay I was attempting to fix that but the latest webtools didn't seem to generate the CSS and I could not find some special routing for it.  This was stated in the other issue.  I believe that there is more than one issue here.

**Comment by fanchyfanch** [comment] 2017-05-16 21:12
Up. :-D

**Comment by sergeyklay** [comment] 2017-05-31 08:56
Fixed in the `3.2.x branch`. Feel free to open new issue if the problem appears again. Thank you for contributing.

**Closed by sergeyklay** 2017-05-31 08:56 UTC
Labels: Need information, WebTools

**Comment by dschissler** [comment] 2017-06-01 01:55
Thanks @sergeysviridenko.  Now the Phalcon team will need to work a bit harder to be able to blame me.
