### ISSUE TITLE
Cannot create model via devtools but can create controller

### ISSUE THREAD

**Issue by advcha** [phalcon/phalcon-devtools#976] opened 2017-02-09 15:59 UTC
I can create controller via the devtools (and webtools) but I can't create model. Here is the command:
```
$ phalcon model products
```
The result:
```
Phalcon DevTools (3.0.4)
Error: Table "products" does not exist. 
```

I also can't do it via webtools. I fill the form like the table name and click 'Generate'. The weird thing happened. it said 'Models were created successfully' but I see nothing.

I also found the url for the webtools is a bit weird (it's working though). when I opened it the first time, the url is like this: http://localhost/works/phalcon/store/public/webtools.php
but after i clicked the others links (do some stuff on controllers, models, system info, etc), the '/webtools.php/' keep added and make the url longer, so it'd be like this: http://localhost/works/phalcon/store/public/webtools.php/webtools.php/webtools.php/webtools.php/webtools.php?_url=/controllers/list. 

Info:
Phalcon DevTools Version:	3.0.4
Phalcon Version:	3.0.3
AdminLTE Version:	2.3.6
OS:	Linux teddy-K43SJ 4.4.0-62-generic #83 14.04.1-Ubuntu SMP Wed Jan 18 18:10:30 UTC 2017 x86_64
PHP Version:	5.6.30-1+deb.sury.org~trusty+1
PHP SAPI:	apache2handler

**Comment by WebworkStudios** [comment] 2017-02-12 17:51
Same problem.

**Comment by DannyVin** [comment] 2017-03-02 21:31
+1.
![02-03-2017 23-16-38](https://cloud.githubusercontent.com/assets/12594208/23527434/985e6a40-ff9e-11e6-8021-abba7e3a3550.jpg)

Configured server with PuPHPet.

> Environment
> OS	Linux apache 4.4.0-45-generic #66-Ubuntu SMP Wed Oct 19 14:12:37 UTC 2016 x86_64
> PHP Version	7.0.16-4+deb.sury.org~xenial+1
> PHP SAPI	fpm-fcgi
> PHP Bin	/usr/sbin/php-fpm7.0
> PHP Extension Dir	/usr/lib/php/20151012
> PHP Bin Dir	/usr/bin
> Loaded PHP config	/etc/php/7.0/fpm/php.ini

app/config/config.php
```

<?php
/*
 * Modified: prepend directory path of current file, because of this file own different ENV under between Apache and command line.
 * NOTE: please remove this comment.
 */
defined('BASE_PATH') || define('BASE_PATH', getenv('BASE_PATH') ?: realpath(dirname(__FILE__) . '/../..'));
defined('APP_PATH') || define('APP_PATH', BASE_PATH . '/app');

return new \Phalcon\Config([
    'database' => [
        'adapter'     => 'Mysql',
        'host'        => 'localhost',
        'username'    => 'dbuser',
        'password'    => '123',
        'dbname'      => 'locdev',
        'charset'     => 'utf8',
    ],
    'application' => [
        'appDir'         => APP_PATH . '/',
        'controllersDir' => APP_PATH . '/controllers/',
        'modelsDir'      => APP_PATH . '/models/',
        'migrationsDir'  => APP_PATH . '/migrations/',
        'viewsDir'       => APP_PATH . '/views/',
        'pluginsDir'     => APP_PATH . '/plugins/',
        'libraryDir'     => APP_PATH . '/library/',
        'cacheDir'       => BASE_PATH . '/cache/',

        // This allows the baseUri to be understand project paths that are not in the root directory
        // of the webpspace.  This will break if the public/index.php entry point is moved or
        // possibly if the web server rewrite rules are changed. This can also be set to a static path.
        //'baseUri'        => preg_replace('/public([\/\\\\])index.php$/', '', $_SERVER["PHP_SELF"]),
        'baseUri' => '/'
    ]
]);


```

`http://localhost/works/phalcon/store/public/webtools.php/webtools.php/webtools.php/webtools.php/webtools.php?_url=/controllers/list.`
Change 'baseUri' to '/' . This may disable adding "/webtools.php/" in end of url.

**Comment by advcha** [comment] 2017-03-03 02:41
Hi @DannyVin, I can't change 'baseUri' to your suggestion. It dont work. Here is my app/config/config.php

```
return new \Phalcon\Config([
   ...
   'application' => [
        ...

        // This allows the baseUri to be understand project paths that are not in the root directory
        // of the webpspace.  This will break if the public/index.php entry point is moved or
        // possibly if the web server rewrite rules are changed. This can also be set to a static path.
        'baseUri'        => preg_replace('/public([\/\\\\])index.php$/', '', $_SERVER["PHP_SELF"]),
        //'baseUri'        => '/',
        'staticUri'      => '/works/phalcon/store/',
    ]
]);
```
If I change it, the url would be like http://localhost/webtools.php?_url=/models. It dont work. the url should be like http://localhost/works/phalcon/store/public/webtools.php?_url=/models

**Comment by DannyVin** [comment] 2017-03-03 09:07
Hi @advcha ,  it's another bug of webtools. I have multiplies url when create project in subfolder of app. "www.app.dev/projectname/" . In Vagrant, I removed folder "app" and create phalcon project with name "app", then changed setting 'baseUri' to '/' . 
I really hope that bugs with models and uri fixed soon.
P.S: Sometimes i have webtools without css or with error 403. I'm killed so many time to fixed this error.

**Comment by le51** [comment] 2017-03-08 11:21
Hi,

for advcha, regarding your urls problems:

* first be sure that you've got .htaccess files in works/phalcon/store and in works/phalcon/store/public
* set baseUri and staticUri to /works/phalcon/store/

**Comment by advcha** [comment] 2017-03-08 14:45
Hi @le51, Thanks for the suggestion. It's working. the url problem is fixed. Here is my final app/config/config.php 
```
return new \Phalcon\Config([
    ...
    'application' => [
        ...
        //'baseUri'        => preg_replace('/public([\/\\\\])index.php$/', '', $_SERVER["PHP_SELF"]),
        'baseUri'          => '/works/phalcon/store',
        'staticUri'        => '/works/phalcon/store/',
    ]
]);
```
Actually the baseUri and staticUri values are not exactly same. To make it work, I removed the last forward slash (/) for baseUri.

**Comment by sergeyklay** [comment] 2017-03-18 08:47
Cc: @dschissler

**Comment by dschissler** [comment] 2017-03-18 22:29
It would be my sacred honor to fix this bug.  Just give me several days to start it.

**Comment by DannyVin** [comment] 2017-03-21 22:20
@dschissler that will be great!

**Comment by dschissler** [comment] 2017-03-21 22:28
I'm squashing bugs today and I'll have a few minutes to start this today but I'll need to play in another VM that I haven't used in a while.

**Comment by dschissler** [comment] 2017-03-21 22:51
I'm first going to fix the baseUri issue with web tools since I was the one who mucked that up.  Then I'll see about the models creation.

**Comment by dschissler** [comment] 2017-03-22 06:01
@sergeyklay I'm not really sure but I think that `public/css` is not being filled with the CSS files when the web tools option is enabled.  I've gone back and forth between looking for the CSS files to be provided by something related to the route and a dynamic PHP interaction and looking for the files to be created during web tools enabling on the command line but I cannot find proof about how it was originally done.  I suspect that something has broken in the webtools generation to create the CSS bundle but I can't know this since I was never a strong user of the web tools.  I also suspect that there are at least two broken issues with the webtools that are possibly outlined in this bug request.  So I ask, is the webtools CSS built when the webtools are enabled or is it created on each request?  I cannot find a route in Phalcon or in the .ht* files that corresponds to this.  Maybe the CSS generation was broken at some point?  Also not to take away from the `baseUri` or `staticUri` issue which seems to have some problems under different circumstances.

**Comment by dschissler** [comment] 2017-04-04 22:08
@sergeyklay Hey so I think that the webtools CSS is not being generated.  Either that or the bundle is built on each execution but then I don't see any routes for that.

**Comment by sergeyklay** [comment] 2017-04-05 10:22
I'll take a look asap

**Comment by mehmetgelmedi** [comment] 2017-07-06 15:21
If you do database config, add the products table with phpMyAdmin or anything

**Comment by sergeyklay** [comment] 2017-07-07 18:49
@sergeysviridenko Could you please take a look

**Comment by sergeysviridenko** [comment] 2017-07-10 13:21
@dschissler Problem with generating CSS and JS files was resolved.

**Comment by sergeysviridenko** [comment] 2017-07-10 13:29
I can't reproduce no one issue.
Phalcon DevTools Version: 3.2.0
Phalcon Version: 3.2.0

@advcha Could you make sure that table `products` is exist? I've tried create model using bash commands `phalcon all-models`, `phalcon model foo-bar` and with `webtools` - all works fine.

**Comment by advcha** [comment] 2017-07-10 13:43
@sergeysviridenko sorry, I haven't got time lately to try the newest phalcon devtools. but if you said this bug don't appear on v3.2.0, it'd be very good. If anyone can confirm this, i'll close this issue.

**Comment by sergeyklay** [comment] 2017-07-19 10:53
Closing, this is fixed. Feel free to open a new issue if the problem appears again. Thank you for contributing.

**Closed by sergeyklay** 2017-07-19 10:53 UTC
Labels: Scaffold

**Comment by ronindesign** [comment] 2018-01-09 22:56
Not sure if this is the same issue, but I'm getting multiplying URI when trying to use phalcon devtools' WebTools.

Example of requested URL when clicking "System Info" from WebTools dashboard:
`http://127.0.0.1:8000/webtools.php/webtools.php?_url=/info`

And, yes, setting `app/config/config.php`:
```php
'application' => [
...
  'baseUri' => '/'
```
fixes this issue.

Additional context:
https://forum.phalconphp.com/discussion/15105/webtools-url-keeps-multiplying

**Comment by JoseB07** [comment] 2018-06-18 20:58
i have this problem anybody can help me with this please


![gg](https://user-images.githubusercontent.com/40371013/41561793-7a483fa4-7310-11e8-8512-49af68a8ebdd.png)

**Comment by sergeysviridenko** [comment] 2018-07-05 10:03
@JoseB07 could you provide your `baseUri`?

**Comment by daviidco** [comment] 2018-11-13 23:40
como? @sergeyklay  a mi me tocó crear el modelo por consola pero me gustaría por el medio gráfico

**Comment by sergeyklay** [comment] 2018-11-14 00:01
C'mon man :) This issue is too old to discuss it now. File a new issue with steps to reproduce and provide screenshots (if any)
