### ISSUE TITLE
Phalcon 3.0.0 Error migrate

### ISSUE THREAD

**Issue by xerron** [phalcon/phalcon-devtools#723] opened 2016-08-03 04:20 UTC
I execute:

phalcon migration --action=generate --version=2   

and show error message:
```
PHP Fatal error:  Uncaught Error: Class 'Phalcon\Version\IncrementalItem' not found in /home/xerron/Repo/php/phalcon-devtools/scripts/Phalcon/Version/ItemCollection.php:76
Stack trace:
#0 /home/xerron/Repo/php/phalcon-devtools/scripts/Phalcon/Migrations.php(95): Phalcon\Version\ItemCollection::createItem('2')
#1 /home/xerron/Repo/php/phalcon-devtools/scripts/Phalcon/Commands/Builtin/Migration.php(129): Phalcon\Migrations::generate(Array)
#2 /home/xerron/Repo/php/phalcon-devtools/scripts/Phalcon/Script.php(125): Phalcon\Commands\Builtin\Migration->run(Array)
#3 /home/xerron/Repo/php/phalcon-devtools/scripts/Phalcon/Script.php(150): Phalcon\Script->dispatch(Object(Phalcon\Commands\Builtin\Migration))
#4 /home/xerron/Repo/php/phalcon-devtools/phalcon.php(88): Phalcon\Script->run()
#5 {main}
  thrown in /home/xerron/Repo/php/phalcon-devtools/scripts/Phalcon/Version/ItemCollection.php on line 76
```

**Comment by sergeyklay** [comment] 2016-08-03 05:18
@xerron Fixed in 3.0.x branch. Could you please check now?

**Comment by xerron** [comment] 2016-08-10 18:00
kill memory.

``` bath
mmap() failed: [12] Cannot allocate memory

mmap() failed: [12] Cannot allocate memory
PHP Fatal error:  Out of memory (allocated 2285903872) (tried to allocate 4294967304 bytes) in /home/xerron/Repo/php/phalcon-devtools/scripts/Phalcon/Version/IncrementalItem.php on line 62
```

**Comment by sergeyklay** [comment] 2016-08-10 18:09
Can't reproduce. Could you please provide full error stack? Can you localize issue? For example run migration with one table in order to find problem.

**Comment by danielsilver2** [comment] 2016-08-16 19:02
I have the same problem with the latest commit.

`PHP Fatal error:  Class 'Phalcon\Version\IncrementalItem' not found in /home/minds04/Projects/010/Gis/vendor/phalcon/devtools/scripts/Phalcon/Version/ItemCollection.php on line 76
PHP Stack trace:
PHP   1. {main}() /home/minds04/Projects/010/Gis/vendor/phalcon/devtools/phalcon.php:0
PHP   2. Phalcon\Script->run() /home/minds04/Projects/010/Gis/vendor/phalcon/devtools/phalcon.php:88
PHP   3. Phalcon\Script->dispatch() /home/minds04/Projects/010/Gis/vendor/phalcon/devtools/scripts/Phalcon/Script.php:150
PHP   4. Phalcon\Commands\Builtin\Migration->run() /home/minds04/Projects/010/Gis/vendor/phalcon/devtools/scripts/Phalcon/Script.php:125
PHP   5. Phalcon\Migrations::run() /home/minds04/Projects/010/Gis/vendor/phalcon/devtools/scripts/Phalcon/Commands/Builtin/Migration.php:142
PHP   6. Phalcon\Mvc\Model\Migration::scanForVersions() /home/minds04/Projects/010/Gis/vendor/phalcon/devtools/scripts/Phalcon/Migrations.php:204
PHP   7. Phalcon\Version\ItemCollection::createItem() /home/minds04/Projects/010/Gis/vendor/phalcon/devtools/scripts/Phalcon/Mvc/Model/Migration.php:516
`

**Comment by sergeyklay** [comment] 2016-08-16 19:09
@danielsilver2 Have you tried Devtools 3.0.x ?

**Comment by Zul3s** [comment] 2016-08-16 20:52
Hi, i have same error, but with Devtools 3.0.x, it's work for me. @sergeyklay Thank you.

**Closed** 2016-08-17 05:09 UTC
Labels: migrations, need script to reproduce
