### ISSUE TITLE
phalcon serve (phalcon-devtools 3.4.0) is looking for .htrouter.php in the wrong place

### ISSUE THREAD

**Issue by yn4v4s** [phalcon/phalcon-devtools#1233] opened 2018-06-12 19:29 UTC
I started using phalconphp framework recently and phalcon-devtools as well, then I have a test project, but when I type `phalcon serve` inside my project's folder and go to http://localhost:8000 I get this output on the shell

![screenshot_20180612_145739](https://user-images.githubusercontent.com/35275827/41312387-ea87db96-6e54-11e8-902c-3f2782b56ccc.png)

but .htroute.php place is project's root istead of public/

**Comment by Ultimater** [comment] 2019-03-05 06:09
I'm also running into this issue. Currently conducting an investigation.

**Comment by Ultimater** [comment] 2019-03-05 11:17
After some investigating, I found that this is an issue caused by PHP itself breaking how the CLI server used to work in a manner that Phalcon was using.

Devtools currently uses the following command:
`php -S 0.0.0.0:8000 -t public .htrouter.php`  
The above command works in php5.6 and in 7.0.12
However it fails for me on 7.0.33 complaining about the directory not being found.
That's the case whether or not the .htrouter.php file contains `/public` in it.

Swapping the order like this ALMOST fixes it:
`php -S 0.0.0.0:8000 .htrouter.php -t public`
That works if the .htrouter.php file contains `/public` in it but doesn't if it doesn't.

After some experimentation, I found the following command which appears to be compatible with both php 5.6 and php 7.0.33:
`php -S 0.0.0.0:8000 -t .htrouter.php -t public`

Ideally we shouldn't need to specify both a router and a home directory. You'd just hard-code `/public` into the .htrouter.php file so you can serve your application like this:
`php -S 0.0.0.0:8000 .htrouter.php`  

However this will run into issues regarding the version of devtools that was used when creating the project as it affects the .htrouter.php file itself.

Pretty sure my hack using two instances of `-t` is the right fix for this.
       
    // scripts/Phalcon/Commands/Builtin/Serve.php
    return sprintf('%s -S %s:%s -t %s -t %s %s',
        $binary_path,
        $this->_hostname,
        $this->_port,
        $this->_base_path,
        $this->_document_root,
        $this->_config
    );

**Comment by Ultimater** [comment] 2019-03-12 08:17
@yn4v4s This issue has been fixed on the 3.4.x branch.

**Comment by Ultimater** [comment] 2019-03-14 07:25
Noticing issues with my solution.  Apparently:  
`php -S 0.0.0.0:8000 -t .htrouter.php -t public`  
actually means:  
`php -S 0.0.0.0:8000 -t public`
It looks like a proper solution would need to detect the PHP version then use either one of the following two commands:  
Older PHP:
`php -S 0.0.0.0:8000 -t public .htrouter.php`
Newer PHP:
`php -S 0.0.0.0:8000 .htrouter.php -t public`

The syntax changed at some point between 7.0.12  and 7.0.33
Would need to figure out exactly what PHP version this changed in so I can code-up a solution that serves up the correct syntax for the PHP version.

**Comment by Ultimater** [comment] 2019-03-19 12:59
This is a known PHP bug apparently:
https://bugs.php.net/bug.php?id=75604
PHP 7.0.25 (and all versions before) looks for the router file relative to the current working directory.  
PHP 7.0.26 looks for the router file relative to the document root.
The old behavior gets stored again via this commit:  
https://github.com/php/php-src/commit/9e98e99a3a88f98d1377d5b2a43b7ad223d8a61f
That would mean checking for which newer PHP versions use that commit when the behavior changed yet again.  Easiest solution here would be to use an absolute path to the router file rather than a relative path so `phalcon serve` works properly under all php versions.

Working on getting such a commit up...

**Comment by Jeckerson** [comment] 2019-06-28 13:30
After some tests with PHP versions, and looking for previous comments. What you just need is update to latest patch PHP version (7.x.patch) and it will work, because it was reverted in next releases.

**Closed by Jeckerson** 2019-06-28 13:30 UTC
Labels: Bug - Medium
