### ISSUE TITLE
hasOne relations not recognized

### ISSUE THREAD

**Issue by cbichis** [phalcon/phalcon-devtools#834] opened 2016-09-17 14:13 UTC
Hello,

DevTools, when generating a model it doesnt seems to recognize the hasOne relations.

Table1: PK id
Table2: PK id

with referential integrity set between them.

is creating rather hasMany/belongsTo relation....

**Comment by sergeyklay** [comment] 2016-09-17 18:36
Could you please steps to reproduce

**Comment by sergeyklay** [comment] 2016-09-25 09:43
@cbichis

**Comment by cbichis** [comment] 2016-09-29 18:26
I need a bit of time to do a sample demo as I noticed this into a complex database.

**Comment by sergeyklay** [comment] 2017-04-30 21:54
I'm closing this issue due to the lack of any reaction. I'll open it again if the need arises

**Closed by sergeyklay** 2017-04-30 21:54 UTC
Labels: Need information, Need script to reproduce
