### ISSUE TITLE
wrong scaffold generation with case sensitive databbase identifiers

### ISSUE THREAD

**Issue by sp4nky** [phalcon/phalcon-devtools#850] opened 2016-09-24 15:56 UTC
Using mysql as database provider and phalcon on linux scaffold generated low case filenames for "views" sub directory while the table name has upper case chars. 
Phalcon wasn't able to resolve the case sensitive view paths.

**Comment by sergeyklay** [comment] 2016-09-24 17:33
@sp4nky Can't reproduce. Could you please provide Devtools version , table schema and command to reproduce?

**Comment by sp4nky** [comment] 2016-09-25 10:24
```
sp4nky@80x:~$ mysql -uroot -p
Enter password: 
Welcome to the MySQL monitor.  Commands end with ; or \g.
Your MySQL connection id is 45
Server version: 5.5.52-0+deb8u1 (Debian)

Copyright (c) 2000, 2016, Oracle and/or its affiliates. All rights reserved.

Oracle is a registered trademark of Oracle Corporation and/or its
affiliates. Other names may be trademarks of their respective
owners.

Type 'help;' or '\h' for help. Type '\c' to clear the current input statement.

mysql> show variables like '%lower_case%';
+------------------------+-------+
| Variable_name          | Value |
+------------------------+-------+
| lower_case_file_system | OFF   |
| lower_case_table_names | 0     |
+------------------------+-------+
2 rows in set (0.00 sec)

mysql> create database test;
Query OK, 1 row affected (0.00 sec)

mysql> use test;
Database changed
mysql> create table Test(id integer, TestName varchar(127));
Query OK, 0 rows affected (0.09 sec)

mysql> exit
Bye
sp4nky@80x:~$ phalcon project Test --enable-webtools

Phalcon DevTools (3.0.1)

                                                         
  Success: Controller "index" was successfully created.  
                                                         
/home/sp4nky/Test/app/controllers/IndexController.php
                                                     
  Success: Project "Test" was successfully created.  
                                                     
sp4nky@80x:~$ cd Test/
sp4nky@80x:~/Test$ vim app/config/config.php 
sp4nky@80x:~/Test$ cd public/
sp4nky@80x:~/Test/public$ php -S 127.0.0.1:8181
PHP 5.6.24-0+deb8u1 Development Server started at Sun Sep 25 11:12:52 2016
Listening on http://127.0.0.1:8181
Document root is /home/sp4nky/Test/public
Press Ctrl-C to quit.
[Sun Sep 25 11:12:59 2016] PHP Warning:  Cannot bind an instance to a static closure in /home/sp4nky/phalcon-devtools/scripts/Phalcon/Web/Tools.php on line 355
[Sun Sep 25 11:12:59 2016] PHP Warning:  Cannot bind an instance to a static closure in /home/sp4nky/phalcon-devtools/scripts/Phalcon/Web/Tools/views/index.phtml on line 15
[Sun Sep 25 11:12:59 2016] 127.0.0.1:38951 [200]: /webtools.php
[Sun Sep 25 11:12:59 2016] 127.0.0.1:38952 [200]: /css/bootstrap/bootstrap.min.css
[Sun Sep 25 11:12:59 2016] 127.0.0.1:38953 [200]: /css/bootstrap/dashboard.css
[Sun Sep 25 11:12:59 2016] 127.0.0.1:38954 [200]: /js/jquery/jquery-3.1.0.min.js
[Sun Sep 25 11:12:59 2016] 127.0.0.1:38955 [200]: /js/bootstrap/bootstrap.min.js
[Sun Sep 25 11:13:02 2016] PHP Warning:  Cannot bind an instance to a static closure in /home/sp4nky/phalcon-devtools/scripts/Phalcon/Web/Tools.php on line 355
[Sun Sep 25 11:13:02 2016] PHP Warning:  Cannot bind an instance to a static closure in /home/sp4nky/phalcon-devtools/scripts/Phalcon/Web/Tools.php on line 190
[Sun Sep 25 11:13:02 2016] PHP Warning:  Cannot bind an instance to a static closure in /home/sp4nky/phalcon-devtools/scripts/Phalcon/Web/Tools/views/scaffold/index.phtml on line 23
[Sun Sep 25 11:13:02 2016] 127.0.0.1:38956 [200]: /webtools.php?_url=/scaffold
[Sun Sep 25 11:13:02 2016] 127.0.0.1:38957 [200]: /css/bootstrap/bootstrap.min.css
[Sun Sep 25 11:13:02 2016] 127.0.0.1:38958 [200]: /css/bootstrap/dashboard.css
[Sun Sep 25 11:13:02 2016] 127.0.0.1:38959 [200]: /js/jquery/jquery-3.1.0.min.js
[Sun Sep 25 11:13:02 2016] 127.0.0.1:38960 [200]: /js/bootstrap/bootstrap.min.js
[Sun Sep 25 11:13:09 2016] PHP Warning:  Cannot bind an instance to a static closure in /home/sp4nky/phalcon-devtools/scripts/Phalcon/Web/Tools.php on line 355
[Sun Sep 25 11:13:09 2016] PHP Warning:  Cannot bind an instance to a static closure in /home/sp4nky/phalcon-devtools/scripts/Phalcon/Builder/Scaffold.php on line 190
[Sun Sep 25 11:13:09 2016] PHP Warning:  Cannot bind an instance to a static closure in /home/sp4nky/phalcon-devtools/scripts/Phalcon/Web/Tools/controllers/ScaffoldController.php on line 85
[Sun Sep 25 11:13:09 2016] PHP Warning:  Cannot bind an instance to a static closure in /home/sp4nky/phalcon-devtools/scripts/Phalcon/Web/Tools/views/scaffold/index.phtml on line 23
[Sun Sep 25 11:13:09 2016] 127.0.0.1:38961 [200]: /webtools.php?_url=/scaffold/generate
[Sun Sep 25 11:13:09 2016] 127.0.0.1:38962 [200]: /css/bootstrap/bootstrap.min.css
[Sun Sep 25 11:13:09 2016] 127.0.0.1:38963 [200]: /css/bootstrap/dashboard.css
[Sun Sep 25 11:13:09 2016] 127.0.0.1:38964 [200]: /js/jquery/jquery-3.1.0.min.js
[Sun Sep 25 11:13:09 2016] 127.0.0.1:38965 [200]: /js/bootstrap/bootstrap.min.js
[Sun Sep 25 11:13:11 2016] PHP Warning:  Cannot bind an instance to a static closure in /home/sp4nky/phalcon-devtools/scripts/Phalcon/Web/Tools.php on line 355
[Sun Sep 25 11:13:11 2016] PHP Warning:  Cannot bind an instance to a static closure in /home/sp4nky/phalcon-devtools/scripts/Phalcon/Web/Tools.php on line 190
[Sun Sep 25 11:13:11 2016] PHP Warning:  Cannot bind an instance to a static closure in /home/sp4nky/phalcon-devtools/scripts/Phalcon/Web/Tools/views/scaffold/index.phtml on line 23
[Sun Sep 25 11:13:11 2016] 127.0.0.1:38966 [200]: /webtools.php?_url=/scaffold
[Sun Sep 25 11:13:11 2016] 127.0.0.1:38967 [200]: /css/bootstrap/bootstrap.min.css
[Sun Sep 25 11:13:11 2016] 127.0.0.1:38968 [200]: /css/bootstrap/dashboard.css
[Sun Sep 25 11:13:11 2016] 127.0.0.1:38969 [200]: /js/jquery/jquery-3.1.0.min.js
[Sun Sep 25 11:13:11 2016] 127.0.0.1:38970 [200]: /js/bootstrap/bootstrap.min.js
^Csp4nky@80x:~/Test/public$ tree ../app/
../app/
├── config
│   ├── config.php
│   ├── loader.php
│   └── services.php
├── controllers
│   ├── ControllerBase.php
│   ├── IndexController.php
│   └── TestController.php
├── library
├── migrations
├── models
│   └── Test.php
└── views
    ├── index
    │   └── index.volt
    ├── index.volt
    ├── layouts
    │   └── test.volt
    └── test
        ├── edit.volt
        ├── index.volt
        ├── new.volt
        └── search.volt

9 directories, 14 files
sp4nky@80x:~/Test/public$ php -S 127.0.0.1:8181
PHP 5.6.24-0+deb8u1 Development Server started at Sun Sep 25 11:14:21 2016
Listening on http://127.0.0.1:8181
Document root is /home/sp4nky/Test/public
Press Ctrl-C to quit.
[Sun Sep 25 11:14:59 2016] 127.0.0.1:38981 [200]: /index.php?_url=/test (succeeds)
[Sun Sep 25 11:15:41 2016] 127.0.0.1:38993 [200]: /index.php?_url=/Test (fails)


```


/index.php?_url=/test (succeeds)
/index.php?_url=/Test (fails)

**Comment by sergeyklay** [comment] 2016-09-25 10:54
@sp4nky Could you please try latest `3.0.x`? Note: you have to disable and enable WebTools again to  fix 
> PHP Warning:  Cannot bind an instance to a static closure in /home/sp4nky/phalcon-devtools/scripts/Phalcon/Web/Tools.php on line 355

**Comment by sp4nky** [comment] 2016-09-25 11:04
Currently using Phalcon DevTools (3.0.1)
Same warnings after disable/enable, view files still doesn't respect database case sensitive table names.

**Comment by sergeyklay** [comment] 2016-09-25 12:28
@sp4nky Did you installed via Composer? It seems Composer doesn't get latest changes from 3.0.x branch. This issue will be fixed in new Devtools release

Try to use this approach https://github.com/phalcon/phalcon-devtools/issues/768#issuecomment-246107825
Or use `git clone -b 3.0.x ...`

**Comment by sergeyklay** [comment] 2016-09-25 13:26
> /index.php?_url=/Test (fails)

Also I'm not sure that this is a problem in the view or case sensitive database settings.
This is typical behavior of the default router config.

The Scaffold component is not intended to create a fully functional website; It is obvious that such things as routing you have to do yourself

**Closed by sergeyklay** 2016-09-25 13:26 UTC
Labels: need information, need script to reproduce
