### ISSUE TITLE
Micro Template issue in notFound declaration

### ISSUE THREAD

**Issue by engsere** [phalcon/phalcon-devtools#971] opened 2017-01-31 07:52 UTC
### Expected and Actual Behavior

using in cli `phalcon project example --type=micro`
devtools correctly create project.
when i type in browser `example.com` it work fine, but when i type `exmaple.com/foo-bar-404-route` i have exception

Default declaration in app.php

```php
$app->notFound(function () {
    $this->response->setStatusCode(404, "Not Found")->sendHeaders();
    echo $this['view']->render('404');
});
```
Correctly declaration in app.php

```php
$app->notFound(function () use ($app) {
    $app->response->setStatusCode(404, "Not Found")->sendHeaders();
    echo $app->view->render('404');
});
```

### Versions:
  Phalcon DevTools Version: 3.0.4
  Phalcon Version: 3.0.3
* Operating System: Linux Mint
* Server: Apache

**Comment by sergeysviridenko** [comment] 2017-07-11 08:52
@engsere Could you provide more information about your issue? I can't reproduce exception. I've no one problem. All works fine.

Phalcon DevTools Version: 3.2.0
Phalcon Version: 3.2.0

**Comment by sergeyklay** [comment] 2017-07-17 13:44
Closing, this is implemented/fixed. Feel free to ping @phalcon/collaborators if the problem appears again. Thank you for contributing.

**Closed by sergeyklay** 2017-07-17 13:44 UTC
