### ISSUE TITLE
Camel-case table names are not reflected in created models

### ISSUE THREAD

**Issue by dstuecken** [phalcon/phalcon-devtools#1143] opened 2017-11-08 10:45 UTC
### Expected and Actual Behavior

I am having a camel-case table name in my mysql database: changeRequests
If I am using the model creator the created model will be named like this: Changerequests.php and Changerequests. So the upper case R is not reflected within the filename and class name.

What I do as a workaround is using the --name flag for model parameter so that I can decide that the model should be named ChangeRequests. But this unfortunately does not work if i'd like to create all models at once with the all-models parameter.

### Details

* Phalcon Framework version: 3.2
* PHP Version: 7.1
* Operating System: Mac OS
* Other related info (Database, table schema): MySQL

**Comment by dstuecken** [comment] 2017-11-08 16:02
Do you guys think I can create a PR for my fix?

**Comment by sergeysviridenko** [comment] 2017-11-09 09:20
@dstuecken I couldn't reproduce this bug with command `phalcon model`. But I could reproduce this with `all-models`. Thank you for report. I'll fix this bug.

**Comment by sergeyklay** [comment] 2017-11-09 15:11
Fixed in the `3.2.x` branch. Feel free to open a new issue if the problem appears again. Thank you for contributing.

**Closed by sergeyklay** 2017-11-09 15:11 UTC
Labels: Models, Scaffold
