### ISSUE TITLE
Field names in generated model do not start as they were defined in MySQL

### ISSUE THREAD

**Issue by jrcscarrillo** [phalcon/phalcon-devtools#1182] opened 2018-02-08 15:11 UTC
I have created this model using the following command:

```bash
phalcon model vendorcredit --get-set
```

My field names in this table start with a uppercase (for instance `TxnID`, `TimeCreated`, `TimeModified` ...), but in generated model the names start with lowercase ( `public $txnID;`, but I expected `public $TxnID;`).

In the past I have created other models but they were created perfectly, my only change since the last time that I had used Phalcon model is that I have migrated from PHP 5.6 to PHP 7.0 (I am using wampserver 3.1.1)

```
Environment:
  OS: Windows NT DESKTOP-IV0QU2J 10.0 build 16299 (Windows 10) AMD64
  PHP Version: 7.0.10
  PHP SAPI: cli
  PHP Bin: C:\wamp64\bin\php\php7.0.10\php.exe
  PHP Extension Dir: C:\php\ext
  PHP Bin Dir: C:\php
  Loaded PHP config: C:\wamp64\bin\php\php7.0.10\php.ini
Versions:
  Phalcon DevTools Version: 3.2.3
  Phalcon Version: 3.2.2
  AdminLTE Version: 2.3.6
```

**Comment by sergeysviridenko** [comment] 2018-02-16 18:15
@jrcscarrillo thank you for report.
Could you provide a little bit more information, data that you had at the start and at the end. Steps to reproduce would be very helpful.
Could you try to use latest stable version?

**Comment by sergeyklay** [comment] 2018-06-07 09:48
I'm closing this issue due to the lack of any reaction. I'll open it again if the need arises

**Closed by sergeyklay** 2018-06-07 09:48 UTC
Labels: Migrations, Models, Need information, Need script to reproduce, Scaffold
