### ISSUE TITLE
Scaffolding does not use namespace on module app-type

### ISSUE THREAD

**Issue by alexglue** [phalcon/phalcon-devtools#320] opened 2015-03-09 22:25 UTC
Webtools scaffolding generates Controllers here:
namespace `MyProject\Frontend\Controllers`;

but those classes does not using namespace `MyProject\Frontend\Controllers`, so i have an error like this:

```
Fatal error: Class 'ControllerBase' not found in
/home/user/proj/myproject/apps/frontend/controllers/UserController.php on line 7
```

**Comment by goorc** [comment] 2015-11-05 10:18
do you fix this error? thanks for sharing answer

**Comment by sergeyklay** [comment] 2017-07-10 17:04
I want to close this issue because I don't understand what exactly happens here. No script to reproduce or relevant information and lack of any reaction. I'll open it again if the need arises

**Closed by sergeyklay** 2017-07-10 17:04 UTC
Labels: Bug - Medium, Scaffold
